# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d34139c02fcdcb5c56e534693621d65e42bd2b6b5b20db72f301f200a2cb8b036cbef89afc573034dd8459d3d36d4ae6484a99ac273bcfa4cecfaf354cf626c0

test:
  secret_key_base: 74add39aec2921a3e253b1b36c186859667295db1b11c3e93ab992c6ee636ceb357f5a190a03f08a66ee227aa5bfc008f7e0b8be09504e57db0d6ffd5583a9b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
